# Generated by Django 5.1.5 on 2025-01-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_user", "can block user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
