# Generated by Django 5.1.5 on 2025-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="table_number",
        ),
        migrations.AddField(
            model_name="reservation",
            name="guests",
            field=models.PositiveIntegerField(
                default="2",
                help_text="Введите количество гостей",
                verbose_name="Количество персон",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                help_text="Введите вашу электронную почту",
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                help_text="Введите ваше имя", max_length=100, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(default="В ожидании", max_length=20),
        ),
    ]
