# Generated by Django 5.1.5 on 2025-01-22 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0003_remove_reservation_table_number_reservation_guests_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.PositiveIntegerField(
                default="2",
                help_text="Введите количество гостей",
                validators=[django.core.validators.MaxValueValidator(25)],
                verbose_name="Количество персон",
            ),
        ),
    ]
