# Generated by Django 5.1.5 on 2025-01-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("В ожидании", "статус: В ожидании"),
                    ("Подтвержден", "статус: Подтвержден"),
                ],
                default="В ожидании",
                max_length=20,
            ),
        ),
    ]
