# Generated by Django 5.1.5 on 2025-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_alter_reservation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=20,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание", verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
