# Generated by Django 5.1.5 on 2025-01-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_restaurant_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.restaurant",
                verbose_name="Ресторан",
            ),
        ),
    ]
