# Generated by Django 5.1.5 on 2025-01-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_reservation_restaurant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["name"],
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["date"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "ordering": ["name"],
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
    ]
