# Generated by Django 5.1.5 on 2025-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0009_alter_contact_options_alter_reservation_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="history",
            field=models.TextField(
                blank=True,
                help_text="Введите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
