# Generated by Django 5.1.5 on 2025-01-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_restaurant_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="mission",
            field=models.TextField(
                blank=True,
                help_text="Введите описание миссии и ценностей",
                null=True,
                verbose_name="Миссия и ценности",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="history",
            field=models.TextField(
                blank=True,
                help_text="Введите описание истории",
                null=True,
                verbose_name="История ресторана",
            ),
        ),
    ]
