# Generated by Django 5.1.5 on 2025-01-28 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0012_alter_reservation_date_alter_reservation_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.PositiveIntegerField(
                default="2",
                validators=[django.core.validators.MaxValueValidator(25)],
                verbose_name="Количество персон",
            ),
        ),
    ]
