# Generated by Django 5.1.5 on 2025-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0013_alter_reservation_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("В ожидании", "статус: В ожидании"),
                    ("Подтвержден", "статус: Подтвержден"),
                    ("Отказано", "статус: Отказано"),
                ],
                default="В ожидании",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
