# Generated by Django 5.1.5 on 2025-01-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0014_alter_reservation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер стола"),
                ),
                ("capacity", models.IntegerField(verbose_name="Вместимость столика")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступность столика"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["reserved_at"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guests",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer_contact",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Контактная информация",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя клиента"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reserved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время бронирования"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.table",
                verbose_name="Номер столика",
            ),
        ),
    ]
