# Generated by Django 5.1.5 on 2025-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0015_table_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["date"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reserved_at",
        ),
        migrations.AddField(
            model_name="reservation",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата бронирования"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время бронирования"
            ),
        ),
    ]
