# Generated by Django 5.1.5 on 2025-01-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0016_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["reserved_at"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="date",
            new_name="reserved_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
    ]
