# Generated by Django 5.1.5 on 2025-01-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0017_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время бронирования"
            ),
        ),
    ]
