# Generated by Django 5.1.5 on 2025-01-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0018_reservation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
    ]
