# Generated by Django 5.1.5 on 2025-01-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0019_remove_reservation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
    ]
