# Generated by Django 4.2.2 on 2025-02-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0021_reservation_owner_restaurant_owner_table_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
