# Generated by Django 4.2.2 on 2025-02-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0023_alter_reservation_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="customer_contact",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="Контактная информация"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer_name",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="Имя клиента"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserved_at",
            field=models.DateTimeField(default="N/A", verbose_name="Дата бронирования"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                default="N/A",
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.table",
                verbose_name="Номер столика",
            ),
        ),
    ]
