# Generated by Django 4.2.2 on 2025-02-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0024_alter_reservation_customer_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="customer_contact",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Контактная информация",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя клиента"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата бронирования"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.table",
                verbose_name="Номер столика",
            ),
        ),
    ]
